deployment/bota/course/urls.py
from django.conf.urls import url
from bota.course import views

app_name = 'course'

urlpatterns = [
    url(r'^$', views.course_main_page, name='index'),
    url(r'((?P<course_id>[A-Z]{3}\d+)/ta$)', views.course_ta),
    url(r'((?P<course_id>[A-Z]{3}\d+)/$)', views.course, name='course'),
    url(r'((?P<course_id>[A-Z]{3}\d+)/in_queue)', views.add_me_to_list),
    url(r'((?P<course_id>[A-Z]{3}\d+)/rm_queue)', views.rm_from_course),
    url(r'((?P<course_id>[A-Z]{3}\d+)/leave_queue)', views.leave_queue),
    url(r'^course_position/$', views.course_position, name='course_position'),
    url(r'^course_next/$', views.course_ta_next, name='course_next'),

]

deployment/bota/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from bota import views

urlpatterns = [
    url(r'^$', views.main_page),
    url(r'^', include('bota.account.urls')),
    url(r'^course', include('bota.course.urls')),
    url(r'^settings', include('bota.app_settings.urls')),

]

#url(r'^login_site$', views.showlogin),
#url(r'^login$', views.login),
#url(r'^$', views.showMainPage),

deployment/bota/course/views.py
from django.shortcuts import render
from .models import Takes, Course, TAin, TATime, Assignment
from bota.course import queue
from django.contrib.auth.decorators import login_required
import datetime


@login_required(login_url='/login/')
def course_main_page(request):
    context = {
        'ta_in': Course.objects.filter(id__in=TAin.objects.filter(user_id=request.user).values("course_id")),
        'courses': Course.objects.filter(id__in=Takes.objects.filter(user_id=request.user).values("course_id")),
        'assignments': get_all_student_assignments(request)
    }
    return render(request, 'main_course_page.html', context)


@login_required(login_url='/login/')
def course(request, course_id):

    ta_times = get_week_times(course_id)
    all_ta_times = get_all_times_after_week(course_id)
    can_enter = check_can_enter(course_id)

    assignments = get_all_course_assignments(course_id)

    course_model = Course.objects.get(course_id=course_id)

    context = {
        'course_model': course_model,
        'course_id': course_id,
        'position': queue.get_position(request.user, course_id),
        'ta_times': ta_times,
        'can_enter': can_enter,
        'assignments': assignments,
        'all_ta_times': all_ta_times,
        'queue_length': queue.get_length(course_id),

    }

    if queue.user_in_queue(request.user, course_id):
        return render(request, 'course_in_queue.html', context)
    return render(request, 'course.html', context)


@login_required(login_url='/login/')
def course_ta(request, course_id):

    username = request.user.username

    if not TAin.objects.filter(course__course_id=course_id, user_id__username=username).exists():
        return course(request, course_id)

    context = {
        'course_id': course_id,
        'next': queue.get_next(course_id),
        'queue_length': queue.get_length(course_id),
        'course_model': Course.objects.get(course_id=course_id),
        'queue_array': get_entire_queue(course_id),
    }
    return render(request, 'course_ta.html', context)


@login_required(login_url='/login/')
def add_me_to_list(request, course_id):
    if check_can_enter(course_id) and not queue.user_in_queue(request.user, course_id):
        queue.add_to_queue(request.user, course_id)
    return course(request, course_id)


@login_required(login_url='/login/')
def rm_from_course(request, course_id):
    queue.rm_from_queue(course_id)
    context = {
        'course_id': course_id,
        'next': queue.get_next(course_id),
        'queue_length': queue.get_length(course_id),
        'course_model': Course.objects.get(course_id=course_id),
        'queue_array': get_entire_queue(course_id),
    }
    return render(request, 'course_ta.html', context)


@login_required(login_url='/login/')
def leave_queue(request, course_id):
    queue.leave_queue(course_id, request.user)

    context = {
        'course_model': Course.objects.get(course_id=course_id),
        'course_id': course_id,
        'position': queue.get_position(request.user, course_id),
        'ta_times': get_week_times(course_id),
        'can_enter': check_can_enter(course_id),
        'assignments': get_all_course_assignments(course_id),
        'all_ta_times': get_all_times_after_week(course_id),
        'queue_length': queue.get_length(course_id),
    }

    return render(request, 'course.html', context)

"""
The two following views are made for the purpose of autorefreshing divs with js.
By creating views, they have separate URLs, with their own POST and GET requests.
This is done so they can be refreshed separately,
"""


def course_position(request):
    #The problem with having a separate view for a _div_
    #is that we can't have a fancy context-based url in urls.py
    #request.META gives the current url path. index [-2] should return the current courseid
    course_id = request.META['HTTP_REFERER'].split('/')[-2]
    position = queue.get_position(request.user, course_id)

    context = {
        'course_model': Course.objects.get(course_id=course_id),
        'position': position,
        'course_id': course_id,
        'queue': queue.get_queue(course_id),

    }
    return render(request, 'course_position_div.html', context)


def course_ta_next(request):
    #The problem with having a separate view for a _div_
    #is that we can't have a fancy context-based url in urls.py
    #request.META gives the current url path. index [-2] should return the current courseid
    course_id = request.META['HTTP_REFERER'].split('/')[-2]
    next_queue = queue.get_next(course_id)
    queue_length = queue.get_length(course_id)

    context = {
        'next': next_queue,
        'queue_length': queue_length,
        'course_model': Course.objects.get(course_id=course_id),
        'course_id': course_id,
        'queue_array': get_entire_queue(course_id),
    }
    return render(request, 'course_ta_next_div.html', context)


"""
Helper functions, not views.
"""


def get_all_times(course_id):
    # Get list of all ta times for course
    try:
        all_ta_times = TATime.objects.filter(course__course_id=course_id).order_by('date')
    except TATime.DoesNotExist:
        all_ta_times = []
    # Remove "old" times from list
    ta_times = []
    for time in all_ta_times:
        if time.date >= datetime.date.today():
            ta_times.append(time)
    return ta_times


def get_all_times_after_week(course_id):
    try:
        all_ta_times = TATime.objects.filter(course__course_id=course_id).order_by('date')
    except TATime.DoesNotExist:
        all_ta_times = []
    # Remove "old" times from list
    ta_times = []
    for time in all_ta_times:
        if time.date.isocalendar()[1] >= datetime.date.today().isocalendar()[1] + 1:
            ta_times.append(time)
    return ta_times


def get_week_times(course_id):
    # Display only current weeks ta times
    ta_times = []
    all_ta_times = get_all_times(course_id)
    for time in all_ta_times:
        if time.date.isocalendar()[1] == datetime.date.today().isocalendar()[1]:
            ta_times.append(time)
    return ta_times


def check_can_enter(course_id):
    ta_times = get_all_times(course_id)
    # Check if there currently is a ta time, i.e. can students enter the queue?
    now = datetime.datetime.today()
    can_enter = False
    for time in ta_times:
        if time.date == now.date():
            if now.time() >= time.start_time and now.time() <= time.end_time:
                can_enter = True
    return can_enter


def get_all_course_assignments(course_id):
    # Get list of all assignments for course
    try:
        all_assignments = Assignment.objects.filter(course__course_id=course_id).order_by('delivery_deadline')
    except Assignment.DoesNotExist:
        all_assignments = []
    # Remove "old" assignments from list
    assignments = []
    for assignment in all_assignments:
        if assignment.demo_deadline >= datetime.datetime.today():
            assignments.append(assignment)
    return assignments


def get_all_student_assignments(request):
    # Get list of all assignments for student
    assignments = []
    try:
        courses = Course.objects.filter(id__in=Takes.objects.filter(user_id=request.user).values("course_id"))
        for course_id in courses:
            course_assignments = get_all_course_assignments(course_id)
            for assignment in course_assignments:
                assignments.append(assignment)
    except Assignment.DoesNotExist:
        assignments = []
    return assignments


def get_entire_queue(course_id):
    queue_array = queue.get_queue(course_id)
    return_queue_array = []
    position = 1
    for student in queue_array:
        string = str(position) + ". " + student
        return_queue_array.append(string)
        position += 1
    return return_queue_array

deployment/bota/course/templates/course.html
{% extends "border_frame.html" %}
{% block title %}{{ course_id }}{% endblock %}

{% block script %}
    <script>
        $("#tatimes").hide();
        $("#display").click(function(){
            $("#tatimes").toggle();
        });
    </script>
{% endblock %}

{% block frame %}

    <h1 style="text-align:center">{{ course_id }} - {{ course_model.name }}</h1>

    <div align="center" style="padding: 5px">
        <h4>Are you waiting for a TA?</h4>
        {% if can_enter %}
        <!--NOTE: Should this to be auto-updated?-->
        <small>Current length of queue: {{ queue_length }}</small>
        <form action="/course/{{ course_id }}/in_queue" method ="post">{% csrf_token %}
            <button  class="form-control btn-enqueue" type="submit" >Put me in the queue!</button>
        </form>
        {% else %}
        <small>There are no TAs currently available, check TA times below for availability</small>
        {% endif %}
    </div>

    <div class ="gridDiv-left">
        <h4><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> TA times:</h4>
        {% if ta_times %}
            <ul class="list-group">
            {% for time in ta_times %}

                    <li class="list-group-item">
                        <h5 class="list-group-item-heading">{{ time.display_week_time }}</h5>
                        <small class="list-group-item-text">{{ time.display_room }}<br />{{ time.display_ta }}</small>
                    </li>
            {% endfor %}
            </ul>
            {% if all_ta_times %}
                <button class="form-control btn-tatimes" id="display" type="button">All TA times</button>
                    <div id="tatimes" style="padding-top: 10px">
                        {% include "ta_time.html"%}
                    </div>
            {% endif %}
        {% else %}
            <p>No times are available.</p>
        {% endif %}

    </div>

    <div class ="gridDiv-right">
        <h4><span class="glyphicon glyphicon-check" aria-hidden="true"></span> Assignments:</h4>
        {% if assignments %}
            <ul class="list-group">
            {% for assignment in assignments %}

                    <li class="list-group-item">
                        <h5 class="list-group-item-heading">{{ assignment.display_name }}</h5>
                        <small class="list-group-item-text">{{ assignment.display_delivery_deadline }}
                            <br />{{ assignment.display_demo_deadline }}</small>
                    </li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No assignments.</p>
        {% endif %}
    </div>

{% endblock %}

deployment/bota/course/templates/course_in_queue.html
{% extends "border_frame.html" %}
{% block script%}

<!--The script is inside the HTML file so that the Jinja2 tag "url" is resolved
This is so we don't need to hardcode the url in-->
<script>
$(document).ready(function() {
    console.log("started script");
    var isAlerted = false;
    var refreshTime = 1000;
    var alertText = "It is your turn! You will be redirected to the main course page.";

    function refreshPos(){
        console.log("refreshed div");
        $.ajax({
            url: '{% url 'course:course_position' %}',
            success: function(data) {
            $('.course_position_div').html(data);
            }
        });

        if (!isAlerted) {
            if ($('.pos0').text().length != 0) {
                alert(alertText);
                isAlerted = true;
                console.log("got here");
                window.location.href = '/course';
            };
        };
    }

    setInterval(function(){refreshPos()}, refreshTime);

});
</script>
{% endblock %}

{% block title %}{{ course_id }}{% endblock %}

{% block frame %}

    <div align="center">
        <h1>{{ course_id }} - {{ course_model.name }}</h1>
        <h3>Queue:</h3>
    </div>

    {% include 'course_position_div.html' %}


{% endblock %}

deployment/bota/course/templates/course_position_div.html
<!--NOTE: jQuery can't select #id elements for some reason. Use class instead-->
<div class="course_position_div" align="center">

    {% if position == 0 %}
       <div class="pos0">
           <p style="font-size:30px">It is your turn! </p>
       </div>
    {% elif position == 1 %}
        <p style="font-size:30px">There is {{ position }} student ahead of you </p>
        <div align="center">
            {% if position > 0 %}
            <form action="/course/{{ course_id }}/leave_queue" method ="post">{% csrf_token %}
                <button  class="form-control btn-leave-queue" type="submit" >Leave queue!</button>
            </form>
            {% endif %}
        </div>
    {% else %}
        <p style="font-size:30px">There are {{ position }} students ahead of you </p>
        <div align="center">
            {% if position > 0 %}
            <form action="/course/{{ course_id }}/leave_queue" method ="post">{% csrf_token %}
                <button  class="form-control btn-leave-queue" type="submit" >Leave queue!</button>
            </form>
            {% endif %}
        </div>
    {% endif %}
</div>

deployment/bota/course/templates/course_ta.html
{% extends "border_frame.html" %}
{% block script%}

<!--The script is inside the HTML file so that the Jinja2 tag "url" is resolved
This is so we don't need to hardcode the url in-->
<script>
$(document).ready(function() {
    console.log("started script");
    var refreshTime = 5000;

    function refreshNext(){
        console.log("refreshed div");
        $.ajax({
            url: '{% url 'course:course_next' %}',
            success: function(data) {
            $('.course_ta_next_div').html(data);
            }
        });

    }

    setInterval(function(){refreshNext()}, refreshTime);

});
</script>
{% endblock %}
{% block title %}{{ course_id }}{% endblock %}
{% block frame %}

        <div align="center">
                <h1>{{ course_id }} - {{ course_model.name }}</h1>
        </div>

        {% include 'course_ta_next_div.html' %}


{% endblock %}

deployment/bota/course/templates/course_ta_next_div.html
<!--NOTE: jQuery can't select #id elements for some reason. Use class instead-->
<div class="course_ta_next_div", align="center">
    <div class="queue-first-place-div">
        <h3>Currently helping: </h3>
        {% if next is none %}
            <p>No one is in queue</p>
        {% else %}
            <h3>1. {{ next }}</h3>
            <p> Queue length: {{ queue_length}} </p>

            <form action="/course/{{ course_id }}/rm_queue" method ="post">{% csrf_token %}
                <button  class="form-control btn-dequeue" type="submit" >Next student!</button>
            </form>
    </div>
    <div class="queue-entire-div">
        <h3>Queue:</h3>
        <p>
        {% for student in queue_array %}
            {{ student }}
            <br />
        {% endfor %}
        </p>
    {% endif %}
    </div>
</div>

deployment/bota/course/templates/main_course_page.html
{% extends "border_frame.html" %}
{% block title %}Courses{% endblock %}
{% block frame  %}
        <div class="gridDivCourse">
                    {% if courses  %}
                         <h3>Student courses:</h3>
                    {% else %}
                        <h3>You have no courses, you can add one under <a href="/settings/edit_course">settings</a></h3>
                    {% endif %}
                    {% for course in courses %}
                        <a style=" text-decoration: none;" href="/course/{{ course }}"><div style="background-color: #3a5c80; margin-bottom: 4px; padding:15px 0 15px 15px" >
                              <h3 style="color: white">{{ course }} - {{ course.name }}</h3>
                        </div></a>
                    {% endfor %}
        </div>
        <div class="gridDivCourse">

                    {% if ta_in%}
                        <h3>TA courses:</h3>
                    {% endif %}
                    {% for course_ta in ta_in %}
                        <a style="text-decoration: none;" href="/course/{{ course_ta }}/ta"><div style="background-color: #3a5c80; margin-bottom: 4px; padding:15px 0 15px 15px" >
                            <h3 style="color: white">{{ course_ta }} - {{ course_ta.name }}</h3>
                        </div></a>
                    {% endfor %}
        </div>

        <div class ="gridDiv-left">
            {% if assignments %}
                <h3><span class="glyphicon glyphicon-check" aria-hidden="true"></span> Assignments:</h3>
            {% else %}
                <h3>You have no assignments</h3>
            {% endif %}
                <ul class="list-group">
                {% for assignment in assignments %}

                        <li class="list-group-item">
                            <h5 class="list-group-item-heading">{{ assignment.display_course }}:
                                {{ assignment.display_name }}</h5>
                            <small class="list-group-item-text">{{ assignment.display_delivery_deadline }}
                                <br />{{ assignment.display_demo_deadline }}</small>
                        </li>

                {% endfor %}
                </ul>
        </div>
    </div>
    {% endblock %}

deployment/bota/course/templates/ta_time.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% if all_ta_times %}
    <ul class="list-group">
    {% for time in all_ta_times %}

            <li class="list-group-item">
                <h5 class="list-group-item-heading">{{ time.display_all_time }}</h5>
                <small class="list-group-item-text">{{ time.display_room }}<br />{{ time.display_ta }}</small>
            </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No TA times are available.</p>
{% endif %}